### PR TITLE
Feature: migrate v1 partner recipes

### LINKED ISSUE #197: v1 recipe has an error having to do with partner packing
## Description
*A clear description of the bug*

File "/home/user/miniconda3/envs/autopack/lib/python3.9/site-packages/cellpack-1.0.3-py3.9.egg/cellpack/autopack/Environment.py", line 395, in set_partners_ingredient
for partner in ingr.partners.all_partners:
AttributeError: 'list' object has no attribute 'all_partners'
See this PR for more info #188 

## Expected Behavior
*What did you expect to happen instead?*

v1 recipes should run without error

## Reproduction
*A minimal example that exhibits the behavior.*

## Environment
*Any additional information about your environment*

### PR DESCRIPTION
**Pull request by rugeli**
Problem
=======
What is the problem this work solves, including
closes #197
closes the open PR #188 

Solution
========
What I/we did to solve this problem
- For consistency with V2 recipes, where `ingr.partners` is `None` instead of an empty list `[]`, I adjusted the ingredient migration in `migrate_v1_to_V2.py`. Now, the partners dict is deleted if no partners exist in V1 recipes.
- Fixed a typo in `migrate_v2_to_V2_1.py`
- Added  the attribute `color` to v1 to v2 name map to ensure it gets migrated
- Added a conditional check to `probability_repelled` for v1 recipes, if it's 0.0, don't reassign `binding_probability`
- Corrected old errors in the test data for partners in `test_recipe_version_migration.py`

## Type of change
Please delete options that are not relevant.

* Bug fix (non-breaking change which fixes an issue)

Steps to Verify:
----------------
1. Pack a v1 recipe:
`pack -r examples/recipes/v1/one_sphere.json -c examples/packing-configs/sparse-packing.json`
`pack -r examples/recipes/v1/partner_packing.json -c examples/packing-configs/sparse-packing.json`

### CODE REVIEW

**Comment by mogres** [comment]
I was able to run both the example recipes in the description. However, even after setting the binding probability to 1, I can still see some of the smaller spheres packing in free space and not next to the partners as they should. 
image

Additionally, it looks like the color for the spheres is not set correctly from the v1 recipe. 

I have attached the slightly modified version of the second recipe mentioned in your description for testing these issues. 
[partner_packing.json](https://github.com/mesoscope/cellpack/files/13232128/partner_packing.json)

Might be something to look into in a separate PR for v1 to v2 conversion.

**Comment by rugeli** [comment]
Thank you so much Saurabh for pointing this out! I've taken a deeper look at our v1 to v2 migration and found a few bugs and attributes(like `color`) that we didn't migrate properly. 

So the current fixes in this PR may not be the best solution if the partners' setups don't work. I'm going to use this branch to implement the feature to migrate v1 partners recipes correctly instead of just addressing the errors. I've switched the PR to draft now and will request review from the team once it's ready.  

PS: the intern version of me showed no mercy to the future me by not commenting the code thoroughly, lesson learned :(

**Comment by rugeli** [comment]
@mogres I'm running your modified version of partner_paking recipe for troubleshooting. Do the results below look right? Or are there any other partner packing issue we should address here? 

binding_probability == 0.5
Screenshot 2023-11-03 at 3 55 16 PM

binding_probability == 1.0
Screenshot 2023-11-03 at 3 55 08 PM

**Comment by mogres** [comment]
@rugeli the updated results look good to me. Thanks for taking a look at this!

**Review by mogres — APPROVED** [review]

**Review by meganrm — APPROVED** [review]

**Pull request merged**
