### PR TITLE
Fix/remove dejavu

### LINKED ISSUE #11: Write out realtime events to simularium file
## Use Case
View realtime packing attempts/ and results. 

## Solution
Save out a simularium file that records all the packing events. Use upy?

## Alternatives
*Please describe any alternatives you've considered, even if you've dismissed them*

### LINKED ISSUE #37: Remove dejavue, replace with simularium helper
## Use Case
In order to run on any machine need to not rely on any mgl_tools

## Solution
*Please describe your ideal solution*

## Alternatives
*Please describe any alternatives you've considered, even if you've dismissed them*

### PR DESCRIPTION
**Pull request by prismofeverything**
Problem
=======
We were unable to run on any os but OSX due to native dependencies in mgtools. 
closes #37 
closes #11 

Solution
========
This removes the associated DejaVu functionality and replaces it with a simularium helper module 

with @meganrm @mogres 

## Type of change

* Bug fix (non-breaking change which fixes an issue)
* New feature (non-breaking change which adds functionality)

Change summary:
---------------
* Pull out just enough DejaVu related functionality to get packing running on ubuntu

Steps to Verify:
----------------
1. run `analyze -o [path/to/output/dir] -p spheresBHT`

newplot

### CODE REVIEW

**Comment by meganrm** [comment]
Here is the realtime packing result: https://simularium.allencell.org/viewer?trajUrl=https://www.dropbox.com/s/vyvgvyuw00h48wg/realtime.simularium.simularium?dl=0

**Comment by mogres** [comment]
Tested by running `analyze -p spheresSST -r cellpack/test-recipes/test_sphere_tree.json -o out` 
Works as expected.

**Review by mogres — APPROVED** [review]
Running `analyze -p spheresSST -r cellpack/test-recipes/test_sphere_tree.json -o out` works as expected.

**Review by prismofeverything — COMMENTED** [review]
Just ran through the code and tests, looks good! Happy to see all the dejavu code is removed.... we'll have to fill out the SimulariumHelper to provide the missing functionality but that can be done in another PR. 

Apparently can't approve my own PR but I do.

**Pull request merged**
