### PR TITLE
Fix gradient inversion

### PR DESCRIPTION
**Pull request by mogres**
Problem
=======
Gradient inversion used distances instead of weights. This could result in unexpected inversion.

Solution
========
The type of inversion can be specified as an option now. `invert: "distance"` inverts the scaled distances and `invert: "weight"` inverts the weights after calculation.

## Type of change
* Bug fix (non-breaking change which fixes an issue)

Change summary:
---------------
* add option to specify inversion using weights or distances
* add default values
* update test recipes to visualize inversion
* add credentials file to gitignore

Steps to Verify:
----------------
1. `pack -r cellpack/tests/recipes/v2/test_mesh_image_gradient.json -c cellpack/tests/packing-configs/test_mesh_config.json`
2. Change `invert: "weight"` to `invert: "distance"` to visualize alternative inversion.

Screenshots:
-----------------------
Inverting distances: 
image

Inverting weights:
image

Keyfiles:
-----------------------
1. Gradient.py

### CODE REVIEW

**Comment by rugeli** [comment]
Looks good to me! I was able to pack the test recipe, however, it's taking a very long time to load the model in Simularium, I'm still waiting to visualize the result. 

One question(might not related to this PR):
In terminal logs, the message `Packing test_mesh_image_gradient_1.0.0:` appeared twice with the first one remaining at 0% progress. Should we make any modifications to address this if one of them is being skipped or something?
Screenshot 2023-09-27 at 2 27 56 PM

**Comment by mogres** [comment]
@rugeli,  were you able to visualize the output? It might help if you change the radius of the `primitive_sphere` to `1` so that there are fewer grid points to visualize.

As for the progress bar, it gets reprinted/interrupted when something else gets printed to the terminal. The `Known pipe types` message seems to have reset the bar -- we can look into what causes that message and whether we can prevent it from being displayed.

**Comment by rugeli** [comment]
> @rugeli, were you able to visualize the output? It might help if you change the radius of the `primitive_sphere` to `1` so that there are fewer grid points to visualize.
> 
> As for the progress bar, it gets reprinted/interrupted when something else gets printed to the terminal. The `Known pipe types` message seems to have reset the bar -- we can look into what causes that message and whether we can prevent it from being displayed.

Thanks for getting back to me! I wasn't able to visualize the output yesterday. I just changed the `primitive_sphere` to `1`, but the simularium has been in loading for the past 20 minutes.

**Comment by mogres** [comment]
@rugeli the recipe has been updated so you should be able to run it faster and visualize in simularium. Let me know if there are still any issues

**Review by meganrm — APPROVED** [review]

**Pull request merged**
