### PR TITLE
Feature/store runs in time

### LINKED ISSUE #36: Use "time" in simularium files to compare different packing runs
## Use Case

Ran multiple packing runs on the same recipe maybe with different inputs or just different seeds and want to compare them 

## Solution

Store a simularium file that has each packing result as a different time point

## Alternatives
*Please describe any alternatives you've considered, even if you've dismissed them*

### PR DESCRIPTION
**Pull request by meganrm**
Problem
=======
closes #36 

Solution
========
created a mapping from seed number to results to store all the objects in one simularium file 
with @mogres @kvegesna @rugeli 

## Type of change
Please delete options that are not relevant.

* New feature (non-breaking change which adds functionality)
* Breaking change (fix or feature that would cause existing functionality to not work as expected)

Steps to Verify:
----------------
1. change the parallel setting to false in the config file 
2. ` pack -r 'cellpack/examples/recipes/v2/one_sphere.json' -c '/cellpack/cellpack/tests/packing-configs/test_parallel_config.json'`
3. should open the _all file in simularium with multiple packings

### CODE REVIEW

**Review by meganrm — COMMENTED** [review]
I can't approve this because I opened the PR, but thanks for the more recent changes Saurabh, they look good to me

**Review by mogres — APPROVED** [review]
#209 has details about a bug while running this in parallel. Other than that, this looks good to go. Very useful update!!

**Review by mogres — CHANGES_REQUESTED** [review]
~~I think we should bring back the check for  `upload_results` option before merging this.~~

Just realized I added this in earlier 😅

**Review by mogres — APPROVED** [review]

**Review by rugeli — APPROVED** [review]

**Comment by rugeli** [comment]
Thank you for adding this feature and the config checks, looks good to me! #209 seems like a good topic for our next group programming session

**Pull request merged**
