### PR TITLE
set staging as the default database for S3 metadata storage

### LINKED ISSUE #233: Proposal: defaulting S3 metadata uploads to staging database
## Use Case
*Please provide a use case to help us understand your request in context*
When executing the `pack` command, the current workflow requires a choice between dev and staging databases for saving S3 metadata. This increases manual intervention and may lead to potential issues, such as #229 

## Solution
*Please describe your ideal solution*
Given that we will be periodically cleaning expired S3 metadata specifically from the staging database, it's logical to direct all S3 metadata to the staging database by default. 

This change will eliminate manual input for database selection during the processing of non-firebase recipe packings. For firebase- related packings, like `upload -r [LOCAL-RECIPE]` or `pack -r [FIREBASE-RECIPE]`, choosing the db to incorporate with will still be required.   

## Alternatives
*Please describe any alternatives you've considered, even if you've dismissed them*
Open to suggestions

### PR DESCRIPTION
**Pull request by rugeli**
Problem
=======
Merge #230 before this PR

What is the problem this work solves, including
closes #233 #229 

Solution
========
What I/we did to solve this problem

- Added logic to initialize firebase handler with the `default_db` parameter if provided and applicable. 
- Set `default_db` to `staging` in `store_metadata()` within the simularium helper. 

## Type of change
Please delete options that are not relevant.

* New feature (non-breaking change which adds functionality)

Change summary:
---------------
* The system will now store S3 metadata in our staging firebase by default for each local packing 

Steps to Verify:
----------------
1. run any local recipe e.g `pack -r examples/recipes/v2/one_sphere.json -c examples/packing-configs/run.json`, it shouldn't prompt you to choose a database 
2. upload a local recipe and run the uploaded recipe to test if this change breaks anything

Screenshots (optional):
-----------------------
Show-n-tell images/animations here
Screenshot 2024-02-27 at 7 11 22 PM

### CODE REVIEW

**Review by meganrm — APPROVED** [review]

**Comment by mogres** [comment]
Running into an error
```
An error occurred while storing the file out/one_sphere/jitter/results_one_sphere_default-run_1.0.0_seed_0.simularium to S3: Failed to initialize a certificate credential. Caused by: "None could not be converted to bytes"
```

while packing the `one_sphere` recipe in the PR description.

I do have firebase credentials and they are being loaded:
```
2024-02-28 15:36:40,857 - botocore.credentials - INFO - credentials.py:1255 -                 load(): Found credentials in shared credentials file: ~/.aws/credentials
```

**Review by mogres — CHANGES_REQUESTED** [review]
Running into an error
```
An error occurred while storing the file out/one_sphere/jitter/results_one_sphere_default-run_1.0.0_seed_0.simularium to S3: Failed to initialize a certificate credential. Caused by: "None could not be converted to bytes"
```

while packing the `one_sphere` recipe in the PR description.

I do have firebase credentials and they are being loaded:
```
2024-02-28 15:36:40,857 - botocore.credentials - INFO - credentials.py:1255 -                 load(): Found credentials in shared credentials file: ~/.aws/credentials
```

**Comment by rugeli** [comment]
> Running into an error
> 
> ```
> An error occurred while storing the file out/one_sphere/jitter/results_one_sphere_default-run_1.0.0_seed_0.simularium to S3: Failed to initialize a certificate credential. Caused by: "None could not be converted to bytes"
> ```
> 
> while packing the `one_sphere` recipe in the PR description.
> 
> I do have firebase credentials and they are being loaded:
> 
> ```
> 2024-02-28 15:36:40,857 - botocore.credentials - INFO - credentials.py:1255 -                 load(): Found credentials in shared credentials file: ~/.aws/credentials
> ```

The loaded botocore credential is for S3, and the error you ran into is from the Google Auth library for Firebase. My guess is that it has something to do with the `.env`  file and how the token is stored, if you could DM me the full error log, we can start ruling out possibilities from there.

And I definitely see how the error messaging could be clearer and more helpful here. I’ll have another pr to explicitly refine error handling for aws and firebase. Thank you for testing and giving feedback!

**Comment by mogres** [comment]
> > Running into an error
> > ```
> > An error occurred while storing the file out/one_sphere/jitter/results_one_sphere_default-run_1.0.0_seed_0.simularium to S3: Failed to initialize a certificate credential. Caused by: "None could not be converted to bytes"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > while packing the `one_sphere` recipe in the PR description.
> > I do have firebase credentials and they are being loaded:
> > ```
> > 2024-02-28 15:36:40,857 - botocore.credentials - INFO - credentials.py:1255 -                 load(): Found credentials in shared credentials file: ~/.aws/credentials
> > ```
> 
> The loaded botocore credential is for S3, and the error you ran into is from the Google Auth library for Firebase. My guess is that it has something to do with the `.env` file and how the token is stored, if you could DM me the full error log, we can start ruling out possibilities from there.
> 
> And I definitely see how the error messaging could be clearer and more helpful here. I’ll have another pr to explicitly refine error handling for aws and firebase. Thank you for testing and giving feedback!

Oops, just noticed the loaded credentials were for aws and not Firebase. My apologies! Will follow up in DM

**Review by mogres — APPROVED** [review]
I am able to run recipes locally and from firebase, and am also able to upload to the staging database. Thanks for the updates!

**Pull request merged**
